# /docker-compose.yml
version: '3.8'

services:
  # Servicio para el backend (FastAPI)
  backend:
    container_name: backend_estudio_contable
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/estudio_contable
    restart: always

  # Servicio para el frontend (Flutter Web)
  frontend:
    container_name: frontend_estudio_contable
    build: 
      context: ./frontend/flutter_gestion_contable
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  # Servicio para la base de datos MySQL
  db:
    container_name: db_estudio_contable
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always

  # Servicio para phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=password
    depends_on:
      - db
    restart: always

volumes:
  mysql_data: