"""Add create-at to Usuario model

Revision ID: 8bb01e8fb525
Revises: 
Create Date: 2025-09-12 17:50:23.307735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8bb01e8fb525'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cliente',
    sa.Column('Cli_ID', sa.Integer(), nullable=False),
    sa.Column('Cli_Nom', sa.String(length=45), nullable=False),
    sa.Column('Cli_Dir', sa.String(length=45), nullable=False),
    sa.Column('Cli_Email', sa.String(length=45), nullable=False),
    sa.Column('Cli_Whatsapp', sa.String(length=45), nullable=False),
    sa.Column('Cli_Contacto', sa.String(length=45), nullable=False),
    sa.Column('Cli_FechaNac', sa.Date(), nullable=False),
    sa.Column('Cli_Saldo', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('Cli_ID')
    )
    op.create_index(op.f('ix_Cliente_Cli_ID'), 'Cliente', ['Cli_ID'], unique=False)
    op.create_table('Usuario',
    sa.Column('usuario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_nombre', sa.String(length=45), nullable=False),
    sa.Column('usuario_email', sa.String(length=45), nullable=False),
    sa.Column('usuario_contraseña', sa.String(length=255), nullable=False),
    sa.Column('usuario_rol', sa.String(length=45), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_index(op.f('ix_Usuario_usuario_email'), 'Usuario', ['usuario_email'], unique=True)
    op.create_index(op.f('ix_Usuario_usuario_id'), 'Usuario', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_Usuario_usuario_nombre'), 'Usuario', ['usuario_nombre'], unique=True)
    op.create_table('Depositos',
    sa.Column('Dep_ID', sa.Integer(), nullable=False),
    sa.Column('Dep_Fecha', sa.Date(), nullable=False),
    sa.Column('Dep_Monto', sa.Float(), nullable=False),
    sa.Column('Dep_Moneda', sa.String(length=5), nullable=False),
    sa.Column('Dep_Referencia', sa.String(length=100), nullable=True),
    sa.Column('Cli_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Cli_ID'], ['Cliente.Cli_ID'], ),
    sa.PrimaryKeyConstraint('Dep_ID')
    )
    op.create_index(op.f('ix_Depositos_Dep_ID'), 'Depositos', ['Dep_ID'], unique=False)
    op.create_table('Impuesto',
    sa.Column('Imp_ID', sa.Integer(), nullable=False),
    sa.Column('Imp_Monto', sa.Float(), nullable=False),
    sa.Column('Imp_Moneda', sa.String(length=4), nullable=False),
    sa.Column('Imp_Frecuencia', sa.Enum('mensual', 'bimestral', 'trimestral', 'anual', name='frecuenciaimpuesto'), nullable=False),
    sa.Column('Imp_Dias', sa.String(length=45), nullable=False),
    sa.Column('Imp_Vencimiento', sa.String(length=45), nullable=False),
    sa.Column('Cli_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Cli_ID'], ['Cliente.Cli_ID'], ),
    sa.PrimaryKeyConstraint('Imp_ID')
    )
    op.create_index(op.f('ix_Impuesto_Imp_ID'), 'Impuesto', ['Imp_ID'], unique=False)
    op.create_table('PasswordResetRequest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['Usuario.usuario_email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PasswordResetRequest_id'), 'PasswordResetRequest', ['id'], unique=False)
    op.create_index(op.f('ix_PasswordResetRequest_token'), 'PasswordResetRequest', ['token'], unique=True)
    op.create_table('Pagos',
    sa.Column('Pago_ID', sa.Integer(), nullable=False),
    sa.Column('Pago_Fecha', sa.Date(), nullable=False),
    sa.Column('Pago_Monto', sa.Float(), nullable=False),
    sa.Column('Cli_ID', sa.Integer(), nullable=False),
    sa.Column('Imp_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Cli_ID'], ['Cliente.Cli_ID'], ),
    sa.ForeignKeyConstraint(['Imp_ID'], ['Impuesto.Imp_ID'], ),
    sa.PrimaryKeyConstraint('Pago_ID')
    )
    op.create_index(op.f('ix_Pagos_Pago_ID'), 'Pagos', ['Pago_ID'], unique=False)
    op.drop_index(op.f('ix_PasswordResetRequest_id'), table_name='passwordresetrequest')
    op.drop_index(op.f('ix_PasswordResetRequest_token'), table_name='passwordresetrequest')
    op.drop_table('passwordresetrequest')
    op.drop_index(op.f('ix_Depositos_Dep_ID'), table_name='depositos')
    op.drop_table('depositos')
    op.drop_index(op.f('ix_impuestos_impuesto_id'), table_name='impuestos')
    op.drop_table('impuestos')
    op.drop_index(op.f('ix_Impuesto_Imp_ID'), table_name='impuesto')
    op.drop_table('impuesto')
    op.drop_index(op.f('ix_Usuario_usuario_email'), table_name='usuario')
    op.drop_index(op.f('ix_Usuario_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_Usuario_usuario_nombre'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_Cliente_Cli_ID'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_Pagos_Pago_ID'), table_name='pagos')
    op.drop_table('pagos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('Pago_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Pago_Fecha', sa.DATE(), nullable=False),
    sa.Column('Pago_Monto', mysql.FLOAT(), nullable=False),
    sa.Column('Cli_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Imp_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Cli_ID'], ['cliente.Cli_ID'], name=op.f('pagos_ibfk_1')),
    sa.ForeignKeyConstraint(['Imp_ID'], ['impuesto.Imp_ID'], name=op.f('pagos_ibfk_2')),
    sa.PrimaryKeyConstraint('Pago_ID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Pagos_Pago_ID'), 'pagos', ['Pago_ID'], unique=False)
    op.create_table('cliente',
    sa.Column('Cli_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Cli_Nom', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('Cli_Dir', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('Cli_Email', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('Cli_Whatsapp', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('Cli_Contacto', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('Cli_FechaNac', sa.DATE(), nullable=True),
    sa.Column('Cli_Saldo', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('Cli_ID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Cliente_Cli_ID'), 'cliente', ['Cli_ID'], unique=False)
    op.create_table('usuario',
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_nombre', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('usuario_email', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('usuario_contraseña', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('usuario_rol', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('usuario_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Usuario_usuario_nombre'), 'usuario', ['usuario_nombre'], unique=True)
    op.create_index(op.f('ix_Usuario_usuario_id'), 'usuario', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_Usuario_usuario_email'), 'usuario', ['usuario_email'], unique=True)
    op.create_table('impuesto',
    sa.Column('Imp_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Imp_Monto', mysql.FLOAT(), nullable=False),
    sa.Column('Imp_Moneda', mysql.VARCHAR(length=4), nullable=False),
    sa.Column('Imp_Frecuencia', mysql.ENUM('mensual', 'bimestral', 'trimestral', 'anual'), nullable=False),
    sa.Column('Imp_Dias', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('Imp_Vencimiento', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('Cli_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Cli_ID'], ['cliente.Cli_ID'], name=op.f('impuesto_ibfk_1')),
    sa.PrimaryKeyConstraint('Imp_ID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Impuesto_Imp_ID'), 'impuesto', ['Imp_ID'], unique=False)
    op.create_table('impuestos',
    sa.Column('impuesto_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('monto', mysql.FLOAT(), nullable=True),
    sa.Column('monto_pago', mysql.FLOAT(), nullable=True),
    sa.Column('honorario', mysql.FLOAT(), nullable=True),
    sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.Cli_ID'], name=op.f('impuestos_ibfk_1')),
    sa.PrimaryKeyConstraint('impuesto_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_impuestos_impuesto_id'), 'impuestos', ['impuesto_id'], unique=False)
    op.create_table('depositos',
    sa.Column('Dep_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Dep_Fecha', sa.DATE(), nullable=False),
    sa.Column('Dep_Monto', mysql.FLOAT(), nullable=False),
    sa.Column('Dep_Moneda', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('Dep_Referencia', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Cli_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Cli_ID'], ['cliente.Cli_ID'], name=op.f('depositos_ibfk_1')),
    sa.PrimaryKeyConstraint('Dep_ID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Depositos_Dep_ID'), 'depositos', ['Dep_ID'], unique=False)
    op.create_table('passwordresetrequest',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['usuario.usuario_email'], name=op.f('passwordresetrequest_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_PasswordResetRequest_token'), 'passwordresetrequest', ['token'], unique=True)
    op.create_index(op.f('ix_PasswordResetRequest_id'), 'passwordresetrequest', ['id'], unique=False)
    op.drop_index(op.f('ix_Pagos_Pago_ID'), table_name='Pagos')
    op.drop_table('Pagos')
    op.drop_index(op.f('ix_PasswordResetRequest_token'), table_name='PasswordResetRequest')
    op.drop_index(op.f('ix_PasswordResetRequest_id'), table_name='PasswordResetRequest')
    op.drop_table('PasswordResetRequest')
    op.drop_index(op.f('ix_Impuesto_Imp_ID'), table_name='Impuesto')
    op.drop_table('Impuesto')
    op.drop_index(op.f('ix_Depositos_Dep_ID'), table_name='Depositos')
    op.drop_table('Depositos')
    op.drop_index(op.f('ix_Usuario_usuario_nombre'), table_name='Usuario')
    op.drop_index(op.f('ix_Usuario_usuario_id'), table_name='Usuario')
    op.drop_index(op.f('ix_Usuario_usuario_email'), table_name='Usuario')
    op.drop_table('Usuario')
    op.drop_index(op.f('ix_Cliente_Cli_ID'), table_name='Cliente')
    op.drop_table('Cliente')
    # ### end Alembic commands ###
