-- MySQL Script generated by MySQL Workbench
-- Fri Jan  2 08:43:39 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema estudioContable
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estudioContable
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estudioContable` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `estudioContable` ;

-- -----------------------------------------------------
-- Table `estudioContable`.`Cliente`
-- Esta tabla tiene todos los datos de los clientes que usan el estudio contable
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudioContable`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `estudioContable`.`Cliente` (
  `Cli_ID` INT NOT NULL AUTO_INCREMENT,
  `Cli_Nom` VARCHAR(45) NOT NULL COMMENT 'Nombre completo del cliete  ',
  `Cli_Dir` VARCHAR(45) NULL COMMENT 'Direccion del cliete',
  `Cli_Email` VARCHAR(45) NULL COMMENT 'Email del Cliente',
  `Cli_Whatsapp` VARCHAR(45) NOT NULL COMMENT 'Whatsap del cliete este dato lo tengo aparte porque el sistema tiene que automaticamente mandar notificaciones  en forma de mensajes a su Whatsapp',
  `Cli_DatoContacto` VARCHAR(45) NULL COMMENT 'Datos de contacto que no son el whatsap para las notificaciones. Puede ser otro Whatsapp o telefono fijo \n',
  `Cli_FechNas` DATE NOT NULL COMMENT 'Fecha de nacimiento del cliete',
  `Cli_Saldo` FLOAT NOT NULL DEFAULT 0 COMMENT 'Saldo actual del cliente, considerando todos los pagos realizados y los impuestos pendientes.',
  PRIMARY KEY (`Cli_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudioContable`.`NombreImpuesto`
-- Esta tabla es para guardar los nombres de los nombre de impuestos y
-- que no se repitan como DGI BPS est estos son unicos y me sirve para filtra etc 
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudioContable`.`NombreImpuesto` ;

CREATE TABLE IF NOT EXISTS `estudioContable`.`NombreImpuesto` (
  `NomIm_Id` INT NOT NULL AUTO_INCREMENT, 
  `NomIm_Txt` VARCHAR(45) NOT NULL COMMENT 'Nombre del impuesto, por ejemplo: DGI, BPS, IRPF, etc.',
  PRIMARY KEY (`NomIm_Id`),
  UNIQUE INDEX `NomIm_Txt_UNIQUE` (`NomIm_Txt` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Se usa para guardar el nombre del impuesto teniendo en cuenta que muchos se repiten es una forma de crear un autocompletar y no digitar más un nombre además queda más fácil para la parte de filtrado';


-- -----------------------------------------------------
-- Table `estudioContable`.`Impuesto`
-- Esta tabla guarda los impuestos que tiene cada cliente
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudioContable`.`Impuesto` ;

CREATE TABLE IF NOT EXISTS `estudioContable`.`Impuesto` (
  `Imp_ID` INT NOT NULL AUTO_INCREMENT,
  `Imp_Monto` FLOAT NOT NULL COMMENT 'Monto original del impuesto a pagar.',
  `Imp_Moneda` VARCHAR(4) NULL DEFAULT 'UYU',
  `Imp_Frecuencia` ENUM('Anual', 'Mensual', 'Semanal', 'Dias') NOT NULL COMMENT 'Frecuencia con la que se debe pagar el impuesto. la idea es usar esta informaicon para gnerar los impuestos automaticamete ',
  `Imp_Dias` INT NULL DEFAULT 0 COMMENT 'Este dato se utiliza cuando se selecciona dias y me da la cantidad de dias para generar el impuesto',
  `Imp_Pago` BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Indica si el impuesto ha sido pagado o no.',
  `Imp_Vencimiento` DATE NOT NULL COMMENT 'Fecha de vencimiento del impuesto',
  `Cli_ID` INT NOT NULL,
  `NomIm_Id` INT NOT NULL,
  PRIMARY KEY (`Imp_ID`),
  INDEX `fk_Impuesto_Cliente_idx` (`Cli_ID` ASC) VISIBLE,
  INDEX `fk_Impuesto_NombreImpuesto1_idx` (`NomIm_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Impuesto_Cliente`
    FOREIGN KEY (`Cli_ID`)
    REFERENCES `estudioContable`.`Cliente` (`Cli_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Impuesto_NombreImpuesto1`
    FOREIGN KEY (`NomIm_Id`)
    REFERENCES `estudioContable`.`NombreImpuesto` (`NomIm_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudioContable`.`Pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudioContable`.`Pagos` ;

CREATE TABLE IF NOT EXISTS `estudioContable`.`Pagos` (
  `pago_id` INT NOT NULL AUTO_INCREMENT,
  `pago_fecha` DATE NOT NULL,
  `pago_monto` FLOAT NOT NULL,
  `Imp_ID` INT NOT NULL,
  `pago_Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`pago_id`),
  INDEX `fk_Pagos_Impuesto1_idx` (`Imp_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pagos_Impuesto1`
    FOREIGN KEY (`Imp_ID`)
    REFERENCES `estudioContable`.`Impuesto` (`Imp_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `estudioContable`.`Alertas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudioContable`.`Alertas` ;

CREATE TABLE IF NOT EXISTS `estudioContable`.`Alertas` (
  `Ale_id` INT NOT NULL AUTO_INCREMENT,
  `Ale_DiasAntes` INT NULL COMMENT 'Dias antes de fecha de alerta',
  `Ale_Fecha` DATE NOT NULL COMMENT 'Fecha para emitir la alerta',
  `Ale_Mensaje` VARCHAR(45) NOT NULL COMMENT 'Mensaje de la alerta',
  PRIMARY KEY (`Ale_id`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudioContable`.`Vencimiento`
-- Estas alertas se generan cuando se crea un impuesto para 
-- avisar que no esta pago
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudioContable`.`Vencimiento` ;

CREATE TABLE IF NOT EXISTS `estudioContable`.`Vencimiento` (
  `Ale_id` INT NOT NULL,
  `Imp_ID` INT NOT NULL,
  INDEX `fk_Vencimiento_Alertas1_idx` (`Ale_id` ASC) VISIBLE,
  PRIMARY KEY (`Ale_id`),
  INDEX `fk_Vencimiento_Impuesto1_idx` (`Imp_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Vencimiento_Alertas1`
    FOREIGN KEY (`Ale_id`)
    REFERENCES `estudioContable`.`Alertas` (`Ale_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vencimiento_Impuesto1`
    FOREIGN KEY (`Imp_ID`)
    REFERENCES `estudioContable`.`Impuesto` (`Imp_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `estudioContable`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudioContable`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `estudioContable`.`Usuario` (
  `Usu_id` INT NOT NULL AUTO_INCREMENT,
  `Usu_nombre` VARCHAR(45) NOT NULL COMMENT 'Nombre de usuario para login',
  `Usu_email` VARCHAR(45) NOT NULL COMMENT 'Email del usuario para contacto y recuperación de contraseña',
  `Usu_password` VARCHAR(255) NOT NULL COMMENT 'Contraseña del usuario',
  `Usu_rol` ENUM('admin', 'user') NOT NULL COMMENT 'Rol del usuario',
  PRIMARY KEY (`Usu_id`),
  UNIQUE INDEX `Usu_nombre_UNIQUE` (`Usu_nombre` ASC) VISIBLE)
  UNIQUE INDEX `Usu_email_UNIQUE` ()
ENGINE = InnoDB;

insert into estudioContable.Usuario 
  (Usu_nombre, Usu_email, Usu_password, Usu_rol) 
  values ('Ary', 'argi.prog@gmail.com', 'hmq7381spudla', 'admin');

-- -----------------------------------------------------
-- Table `estudioContable`.`PasswordResetRequest`
-- Tabla de Soporte para Reseteo de Clave
-- -----------------------------------------------------

DROP TABLE IF EXISTS PasswordResetRequest;

-- Tabla de Soporte para Reseteo de Clave
CREATE TABLE PasswordResetRequest (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(45) NOT NULL,
    token VARCHAR(255) UNIQUE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL,
    CONSTRAINT fk_usuario_email FOREIGN KEY (email) REFERENCES Usuario(Usu_email) ON DELETE CASCADE
);


-- -----------------------------------------------------
-- Table `estudioContable`.`Eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudioContable`.`Eventos` ;

CREATE TABLE IF NOT EXISTS `estudioContable`.`Eventos` (
  `Ale_id` INT NOT NULL,
  `Cli_ID` INT NOT NULL,
  INDEX `fk_Eventos_Alertas_idx` (`Ale_id` ASC) VISIBLE,
  INDEX `fk_Eventos_Clientes_idx` (`Cli_ID` ASC) VISIBLE,
  PRIMARY KEY (`Ale_id`),
  CONSTRAINT `fk_Eventos_Alertas`
    FOREIGN KEY (`Ale_id`)
    REFERENCES `estudioContable`.`Alertas` (`Ale_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eventos_Clientes`
    FOREIGN KEY (`Cli_ID`)
    REFERENCES `estudioContable`.`Cliente` (`Cli_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `estudioContable`.`Cuentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudioContable`.`Cuentas` ;

CREATE TABLE IF NOT EXISTS `estudioContable`.`Cuentas` (
  `Cuenta_ID` INT NOT NULL AUTO_INCREMENT,
  `Cuenta_Nombre` VARCHAR(45) NULL,
  `Cuenta_Monto` FLOAT NULL,
  PRIMARY KEY (`Cuenta_ID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `estudioContable`.`Deposito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudioContable`.`Deposito` ;

CREATE TABLE IF NOT EXISTS `estudioContable`.`Deposito` (
  `Dep_ID` INT NOT NULL AUTO_INCREMENT,
  `Dep_Descricion` VARCHAR(45) NULL,
  `Dep_Monto` FLOAT NOT NULL,
  `Impuesto_Imp_ID` INT NOT NULL,
  `Dep_Fech` DATE NOT NULL,
  PRIMARY KEY (`Dep_ID`),
  INDEX `fk_Deposito_Impuesto1_idx` (`Impuesto_Imp_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Deposito_Impuesto1`
    FOREIGN KEY (`Impuesto_Imp_ID`)
    REFERENCES `estudioContable`.`Impuesto` (`Imp_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Esta tabla guarda los pagos de los impustos que se acer para los diferentes impuestos \n';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;